jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:3306/green_farming_platform?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
jdbc.username=root
jdbc.password=1940286621
jdbc.initialSize=3
jdbc.minIdle=3
jdbc.maxActive=20
jdbc.maxWait=60000
